### PR TITLE
Dark Mode Functionality added

### PR DESCRIPTION
**Pull request by Rickey07**
Hi ,

I've added the dark mode functionality in the app. It was quite uneasy task to add the same because dark mode feature on the UI for overall app was not an good option. So I've created the same for main data-weather-component. Please check the same!

Attaching the screenshot for your reference!:- 

Light Mode:- 
Light-mode-weather-wizard-app

Dark Mode:- 
dark-mode-weather-wizard-app

Please check the same!

### CODE REVIEW

**Comment by codewizard26** [comment]
I think you haven't pulled the last changes to your local repository and you are working on some older version which is different from master branch which is creating conflicts, for reference its {min_temp} which was fixed is the last version but still in your code its {mintemp}. so would request you to make changes accordingly so that code doesn't breaks

**Comment by codewizard26** [comment]
you can check above netlify deploy preview its not showing minimum temperature value where as in master it is fixed

**Comment by Rickey07** [comment]
Hi Please find the updated one with resolved bug.

updated-dark-mode

**Comment by codewizard26** [comment]
great work, merging the pr

**Pull request merged**
