### PR TITLE
Logo Added, UX fixed, Navbar added

### PR DESCRIPTION
**Pull request by TheDemantor**
Please add these changes if it suites you. If you have any issue please contact me.

### CODE REVIEW

**Comment by TheDemantor** [comment]
image
It looks like this now

**Comment by KritikaJoshi22** [comment]
Modify the search button and reduce the font size of the placeholder.

**Comment by TheDemantor** [comment]
image
Is it good now??

**Comment by TheDemantor** [comment]
It's done now. Please review and merge.

**Comment by TheDemantor** [comment]
If you want any changes please contact. If it is good, please merge.

**Comment by codewizard26** [comment]
please add icon.png file in your project displaying the current ui of the project for other contributors. and we will merge it
Thanks

**Comment by TheDemantor** [comment]
Done, anything else??

**Comment by codewizard26** [comment]
looks good ...thanks for the contribution

**Pull request merged**
